<?php

namespace MainBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getPlaceByPosition($position, $enabled) {
        $qb = $this
            ->createQueryBuilder('p')
            ->where('p.enabled = :enabled')
                ->setParameter('enabled', $enabled)
            ->leftJoin('p.level', 'level')
                ->addSelect('level')
            ->andWhere('level.position <= :position')
                ->setParameter('position', $position)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }


}
